### ISSUE TITLE
Add country dropdown to first survey page

### ISSUE THREAD

**Issue by MiroslavStanik** [checkifcovid/survey-app#2]
User should be able to select country of residence

**Comment by zzmarkzz321** [comment]
Definitely should collect country as a data point. Im not sure how we plan on collecting their location (whether by geolocation or simply asking), so we'll see how things play out. Good call out!

**Comment by iwoork** [comment]
The country is configured on `next.config.js` file. Each country now is a separate deployment so we can handle differences separately (e.g contact number, language, etc). See this code block:

https://github.com/checkifcovid/survey-app/blob/master/next.config.js#L5-L18
