### ISSUE TITLE
Footer Component

### ISSUE THREAD

**Issue by zzmarkzz321** [checkifcovid/survey-app#8]
<img width="1266" alt="Screen Shot 2020-03-28 at 9 57 48 AM" src="https://user-images.githubusercontent.com/6733939/77828757-9bf61a80-70da-11ea-98b7-f9a082e8297d.png">

example: https://app.zeplin.io/project/5e7d50248302c78f5fa0de84/screen/5e7e55463ec9d76c338dd26e

**Comment by iwoork** [comment]
Closing this. This is now live.
